version: '3.4'

services:
    evoting.api:
        image: evotingapi
        build:
            context: .
            dockerfile: eVoting.Api/Dockerfile
        ports:
            - "5001:80"
        depends_on:
            - "rabbitmq"
            - "db"
        environment:
            - MT_TRANSPORT=RMQ
            - MT_RMQ__HOST=rabbitmq
        logging:
            driver: gelf
            options:
                gelf-address: "udp://localhost:12201"
                tag: "evoting.api"
        restart: always

    evoting.worker:
        image: evotingworker
        build:
            context: .
            dockerfile: eVoting.Worker/Dockerfile
        depends_on:
            - "rabbitmq"
            - "db"
        environment:
            - MT_TRANSPORT=RMQ
            - MT_RMQ__HOST=rabbitmq
            - DB_CONNECTION=Host=db;Database=evoting2;Username=evoting;Password=evotingadmin
        logging:
            driver: gelf
            options:
                gelf-address: "udp://localhost:12201"
                tag: "evoting.worker"
        restart: always

    evoting.result.api:
        image: evotingresultapi
        build:
            context: .
            dockerfile: eVoting.Result.Api/Dockerfile
        ports:
            - "5002:80"
        depends_on:
            - "db"
        environment:
            - DB_CONNECTION=Host=db;Database=evoting2;Username=evoting;Password=evotingadmin
        logging:
            driver: gelf
            options:
                gelf-address: "udp://localhost:12201"
                tag: "evoting.result.api"
        restart: always

    rabbitmq:
        image: masstransit/rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"

    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=evoting
            - POSTGRES_PASSWORD=evotingadmin

    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - "db"

    redis-cache:
        image: redis:6.2
    
    elasticsearch:
        image: elasticsearch:7.11.1
        environment:
            - discovery.type=single-node
        volumes:
            - ./elk/elasticsearch_data/:/usr/share/elasticsearch/data
        mem_limit: "1g"

    logstash-agent:
        image: logstash:7.11.1
        volumes:
            - ./elk/logstash-agent:/etc/logstash
        command: logstash -f /etc/logstash/logstash.conf
        depends_on:
            - elasticsearch
        ports:
            - 12201:12201/udp

    logstash-central:
        image: logstash:7.11.1
        volumes:
            - ./elk/logstash-central:/etc/logstash
        command: logstash -f /etc/logstash/logstash.conf
        depends_on:
            - elasticsearch

    kibana:
        image: kibana:7.11.1
        ports:
            - 5601:5601
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        depends_on:
            - elasticsearch

